{
  ":authority": "i.instagram.com",
  ":method": "POST",
  ":path": "/api/v1/bloks/apps/com.bloks.www.bloks.caa.login.async.send_login_request/",
  ":scheme": "https",
  "x-ig-app-locale": "in_ID",
  "x-ig-device-locale": "in_ID",
  "x-ig-mapped-locale": "id_ID",
  "x-pigeon-session-id": f"UFS-{str(uuid.uuid4())}-3",
  "x-pigeon-rawclienttime": "{:.3f}".format(time.time()),
  "x-ig-bandwidth-speed-kbps": "-1.000",
  "x-ig-bandwidth-totalbytes-b": "0",
  "x-ig-bandwidth-totaltime-ms": "0",
  "x-bloks-version-id": self.Blok_ID(),
  "x-ig-www-claim": "0",
  "x-bloks-is-layout-rtl": "false",
  "x-ig-device-id": "cbb30751-e663-4e9c-8a3c-1b33901ed084",
  "x-ig-family-device-id": "98ccf8dc-1ecc-4663-9077-2d18309090f0",
  "x-ig-android-id": "android-4aca695260085376",
  "x-ig-timezone-offset": "25200",
  "x-fb-connection-type": "MOBILE.LTE",
  "x-ig-connection-type": "MOBILE(LTE)",
  "x-ig-capabilities": "3brTv10=",
  "x-ig-app-id": "3419628305025917",
  "priority": "u=3",
  "user-agent": "Barcelona 289.0.0.77.109 Android (30/11; 230dpi; 720x1481; realme; RMX2195; RECE4244; qcom; in_ID; 489720138)",
  "accept-language": "id-ID, en-US",
  "x-mid": str(self.SetMid()),
  "ig-intended-user-id": "0",
  "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
  "content-length": "3136",
  "accept-encoding": "zstd, gzip, deflate",
  "x-fb-http-engine": "Liger",
  "x-fb-client-ip": "True",
  "x-fb-server-cluster": "True"
}

def HeadersApiLogin(self):
       return {
          'host': 'b.i.instagram.com',
          'x-ig-app-locale': 'in_ID',
          'x-ig-device-locale': 'in_ID',
          'x-ig-mapped-locale': 'id_ID',
          'x-pigeon-session-id': f'UFS-{str(uuid.uuid4())}-3',
          'x-pigeon-rawclienttime': '{:.3f}'.format(time.time()),
          'x-ig-bandwidth-speed-kbps': '-1.000',
          'x-ig-bandwidth-totalbytes-b': '0',
          'x-ig-bandwidth-totaltime-ms': '0',
          'x-bloks-version-id': self.Blok_ID(),
          'x-bloks-is-prism-enabled': 'false',
          'x-bloks-is-layout-rtl': 'false',
          'x-ig-device-id': 'c1e3a60f-2663-465a-8807-72127dd9c217',
          'x-ig-family-device-id': '83139772-1c69-44ff-89df-c0bfb4913b69',
          'x-ig-android-id': 'android-4aca695260085376',
          'x-ig-timezone-offset': str(self.timezone_offset()),
          'x-fb-connection-type': 'MOBILE.LTE',
          'x-ig-connection-type': 'MOBILE(LTE)',
          'x-ig-capabilities': '3brTv10=',
          'x-ig-app-id': '3419628305025917',
          'priority': 'u=3',
          'user-agent': 'Instagram 312.1.0.34.111 Android (30/11; 320dpi; 720x1472; INFINIX MOBILITY LIMITED/Infinix; Infinix X688B; Infinix-X688B; mt6765; en_US; 548323754)',
          'accept-language': 'id-ID, en-US',
          'x-mid': str(self.SetMid()),
          'ig-intended-user-id': '0',
          'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
          'content-length': '3146',
          'x-fb-http-engine': 'Liger',
          'x-fb-client-ip': 'True',
          'x-fb-server-cluster': 'True'
       }